### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen - .../cache/saml/metadata/Influitive-AdvocateHub)

### ISSUE THREAD

**Issue by heaven** [sportngin/saml_idp#16]
Subj, what should be there?

```
Errno::ENOENT (No such file or directory @ rb_sysopen - /var/www/crm.wegohealth.com/releases/20150218112304/cache/saml/metadata/Influitive-AdvocateHub):
  config/initializers/saml_idp.rb:118:in `initialize'
  config/initializers/saml_idp.rb:118:in `open'
  config/initializers/saml_idp.rb:118:in `block (2 levels) in <top (required)>'
  lib/response_timer.rb:21:in `call'
  lib/core_ext/thread.rb:16:in `call'
  lib/core_ext/thread.rb:16:in `block in initialize'
```

**Comment by TJM** [comment]
We are getting a similar error. The problem *appears* to be that the "metadata_persister" is not running before the "metadata_getter" runs

**Comment by jphenow** [comment]
can you provide some truncated version of the initializer? I think I'm missing something

**Comment by TJM** [comment]
I had to change the initializer to read:

```
  # `identifier` is the entity_id or issuer of the Service Provider,
  # `service_provider` is a ServiceProvider object. Based on the `identifier` or the
  # `service_provider` you should return the settings.to_h from above
  config.service_provider.persisted_metadata_getter = ->(identifier, service_provider){
    fname = identifier.to_s.gsub(/\/|:/,"_")
    `mkdir -p #{Rails.root.join("cache/saml/metadata")}`
    if File.file?(Rails.root.join("cache/saml/metadata/#{fname}"))
      File.open Rails.root.join("cache/saml/metadata/#{fname}"), "rb" do |f|
        Marshal.load f
      end
    end
  }
```

**Comment by TJM** [comment]
@jphenow was my comment sufficient for you to update the README (example) or should I try to submit a pull request.

**Comment by jphenow** [comment]
Oh cripes, my bad.

I'll take a look at your PR and we'll wrap it up there.

**Comment by jphenow** [comment]
Ah, derping this morning. Also not a PR.

Writing up a change to the README now

**Comment by jphenow** [comment]
@TJM please see #24
